services:
  - type: web
    name: terabox-downloader
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y wget libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libdrm2 libxcomposite1 libxrandr2 libgbm1 libasound2 libxdamage1 libxfixes3 libxshmfence1 libx11-xcb1 libxtst6 libglib2.0-0 libnss3 libxss1 libgtk-3-0
      pip install -r requirements.txt
      playwright install
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
